title: "Stellar Hugo Theme"
paginate: 8
relativeURLs: true

theme:
- Stellar-Hugo-Theme

markup:
  _merge: deep

params:
  author: Steven
  avatar: /logo.png
  logo: /logo.png

  description:
  - "Bio & IT 爱好者"
  - '欢迎关注个人语雀知识库'

  notice:
  - "个人主站点：[语雀](https://weiyan.cc)"
  - "本站使用 Hugo 搭建，移植了 [Hugo Stellar](https://github.com/Yharimium/hugo-stellar) 主题，并有所[改动](https://github.com/shenweiyan/Stellar-Hugo-Theme)"

  copyright: "&copy; Powered by [Stellar-Hugo-Theme](https://github.com/shenweiyan/Stellar-Hugo-Theme) and  [Hugo](https://gohugo.io) | [Bio IT 爱好者](https://www.bioitee.com/) 2023 - 2023 | [粤ICP备16023717号](http://beian.miit.gov.cn/)"

  tencentUrl: true
  autoInvert: true

  social:
  - name: "语雀"
    url: "https://www.yuque.com/shenweiyan"
    icon: "fa-solid fa-crow"
  - name: "GitHub"
    url: "https://github.com/shenweiyan"
    icon: "fa-brands fa-square-github"
  - name: "微信公众号"
    url: "https://space.bilibili.com/"
    icon: "fa-brands fa-weixin"

menus:
  main:
  - name: "博客"
    weight: 1
    url: "/"
    params:
      tabs:
      - name: "所有文章"
        url: "/"
      - name: "分类"
        url: "/categories/"
      - name: "标签"
        url: "/tags/"
      - name: "归档"
        url: "/archives/"
  - name: "文档"
    weight: 2
    url: "/docs/"
    params:
      tabs:
      - name: "所有文档"
        url: "/docs/"
  - name: "搜索"
    weight: 3
    url: "/search/"
    params:
      tabs:
      - name: "博客搜索"
        url: "/search/?sec=posts"
      - name: "文档搜索"
        url: "/search/?sec=docs"
  - name: "关于"
    weight: 4
    url: "/about/"
    params:
      tabs:
      - name: "About Hugo"
        url: "/about/#about-hugo"
